name: Blue Green Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "deploy or rollback"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - rollback

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 by SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/blue-green
            git pull origin main

            if [ "${{ github.event.inputs.action }}" = "rollback" ]; then
              chmod +x scripts/rollback.sh
              ./scripts/rollback.sh
            else
              chmod +x scripts/deploy-blue-green.sh
              ./scripts/deploy-blue-green.sh
            fi

            curl -f http://localhost:8080/health